import React, { useRef, useState } from 'react';
import { Download, FileText } from 'lucide-react';
import { jsPDF } from 'jspdf';
import html2canvas from 'html2canvas';

// A hidden component styled for the PDF output
const PrintableReport = React.forwardRef(({ queryResult, fileName }, ref) => {
  if (!queryResult) return null;

  return (
    <div ref={ref} className="printable-report">
      <div className="report-header">
        <h1>UFDR Analysis Report</h1>
        <p><strong>Data Source:</strong> {fileName || 'Unknown'}</p>
        <p><strong>Generated on:</strong> {new Date().toLocaleString()}</p>
      </div>

      <div className="report-section">
        <h2>Query Executed</h2>
        <p className="query-text">"{queryResult.query}"</p>
      </div>
      
      {/* FIX: Check if insights array exists and has content before rendering */}
      {(queryResult.insights || []).length > 0 && (
        <div className="report-section">
          <h2>Key Insights</h2>
          <ul>
            {/* FIX: Use '|| []' to prevent crash if insights is missing */}
            {(queryResult.insights || []).map((insight, index) => (
              <li key={index}>{insight}</li>
            ))}
          </ul>
        </div>
      )}

      <div className="report-section">
        <h2>Detailed Records</h2>
        <table className="report-table">
          <thead>
            <tr>
              <th>Timestamp</th>
              <th>Type</th>
              <th>Direction</th>
              <th>From</th>
              <th>To</th>
              <th>Location</th>
            </tr>
          </thead>
          <tbody>
            {/* FIX: Add 'index' and use '|| []' to prevent crash and warnings */}
            {(queryResult.callLogs || []).map((log, index) => (
              // FIX: Use index as the key
              <tr key={index}>
                <td>{new Date(log.timestamp).toLocaleString()}</td>
                <td>{log.callType}</td>
                <td>{log.direction}</td>
                <td>{log.caller_number}</td>
                <td>{log.receiver_number}</td>
                <td>{log.location}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
       <div className="report-footer">
        <p>Report generated by UFDR Analysis Tool</p>
      </div>
    </div>
  );
});

const ReportDownload = ({ queryResult, fileName }) => {
  const reportRef = useRef(null);
  const [isGenerating, setIsGenerating] = useState(false);

  const generatePDFReport = async () => {
    if (!queryResult || !reportRef.current) {
      alert('No data available to generate report');
      return;
    }

    setIsGenerating(true);
    
    try {
      const canvas = await html2canvas(reportRef.current, {
        scale: 2, 
        useCORS: true,
      });

      const imgData = canvas.toDataURL('image/png');
      const pdf = new jsPDF({
        orientation: 'portrait',
        unit: 'px',
        format: [canvas.width, canvas.height],
      });

      pdf.addImage(imgData, 'PNG', 0, 0, canvas.width, canvas.height);
      const pdfFileName = `${fileName ? fileName.replace(/\.[^/.]+$/, "") : "UFDR"}_Report.pdf`;
      pdf.save(pdfFileName);

    } catch (error) {
      console.error("Failed to generate PDF:", error);
      alert("An error occurred while generating the PDF.");
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <>
      <div style={{ position: 'absolute', left: '-9999px', top: 0 }}>
        <PrintableReport ref={reportRef} queryResult={queryResult} fileName={fileName} />
      </div>

      <div className="report-download-container">
        <button
          type="button"
          className="report-download-button"
          onClick={generatePDFReport}
          disabled={!queryResult || isGenerating}
        >
          <Download className="download-icon" />
          {isGenerating ? 'Generating PDF...' : 'Download Report as PDF'}
          <FileText className="report-icon" />
        </button>
        {!queryResult && (
          <p className="report-download-help">
            Execute a query to generate downloadable report
          </p>
        )}
      </div>
    </>
  );
};

export default ReportDownload;