import React, { useRef, useState } from 'react';
import { Download, FileText } from 'lucide-react';
import { jsPDF } from 'jspdf';
import html2canvas from 'html2canvas';

// A hidden component styled for the PDF output
const PrintableReport = React.forwardRef(({ queryResult, fileName }, ref) => {
  if (!queryResult) return null;

  const formatDuration = (seconds) => {
    if (seconds === null || seconds === undefined || seconds === 0) return 'N/A';
    const minutes = Math.floor(seconds / 60);
    const remainingSeconds = seconds % 60;
    return `${minutes}:${remainingSeconds.toString().padStart(2, '0')}`;
  };

  // --- STYLES for black table with white text ---
  const tableStyle = {
    width: '100%',
    backgroundColor: '#000000',
    borderCollapse: 'collapse',
    fontFamily: 'Arial, sans-serif',
    fontSize: '10pt',
  };

  const thStyle = {
    backgroundColor: '#000000',
    borderBottom: '1px solid #555555',
    padding: '10px 8px',
    textAlign: 'left',
    fontWeight: 'bold',
    color: '#FFFFFF',
  };

  const tdStyle = {
    padding: '10px 8px',
    textAlign: 'left',
    borderBottom: '1px solid #333333',
    backgroundColor: '#000000',
    color: '#FFFFFF',
  };

  return (
    <div ref={ref} className="printable-report" style={{ padding: '40px', backgroundColor: 'white', color: 'black' }}>
      <div className="report-header">
        <h1>UFDR Analysis Report</h1>
        <p><strong>Data Source:</strong> {fileName || 'Unknown'}</p>
        <p><strong>Generated on:</strong> {new Date().toLocaleString()}</p>
      </div>

      <div className="report-section" style={{ marginTop: '20px' }}>
        <h2>Query Executed</h2>
        <p className="query-text">"{queryResult.query}"</p>
      </div>

      {(queryResult.insights || []).length > 0 && (
        <div className="report-section" style={{ marginTop: '20px' }}>
          <h2>Key Insights</h2>
          <ul>
            {(queryResult.insights || []).map((insight, index) => (
              <li key={index}>{insight}</li>
            ))}
          </ul>
        </div>
      )}

      <div className="report-section" style={{ marginTop: '20px' }}>
        <h2>Detailed Records</h2>
        <table className="report-table" style={tableStyle}>
          <thead>
            <tr>
              <th style={thStyle}>Timestamp</th>
              <th style={thStyle}>Type</th>
              <th style={thStyle}>Caller</th>
              <th style={thStyle}>Callee</th>
              <th style={thStyle}>Duration</th>
              <th style={thStyle}>Location</th>
            </tr>
          </thead>
          <tbody>
            {(queryResult.callLogs || []).map((log, index) => (
              <tr key={index}>
                <td style={tdStyle}>{new Date(log.start_time).toLocaleString()}</td>
                <td style={tdStyle}>{log.call_type || "N/A"}</td>
                <td style={tdStyle}>{log.caller || "Unknown"}</td>
                <td style={tdStyle}>{log.callee || "Unknown"}</td>
                <td style={tdStyle}>{formatDuration(log.duration_seconds)}</td>
                <td style={tdStyle}>{log.location || "N/A"}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      <div className="report-footer" style={{ marginTop: '20px' }}>
        <p>Report generated by UFDR Analysis Tool</p>
      </div>
    </div>
  );
});

const ReportDownload = ({ queryResult, fileName }) => {
  const reportRef = useRef(null);
  const [isGenerating, setIsGenerating] = useState(false);

  const generatePDFReport = async () => {
    if (!queryResult || !reportRef.current) {
      alert('No data available to generate report');
      return;
    }

    setIsGenerating(true);

    try {
      const canvas = await html2canvas(reportRef.current, {
        scale: 2,
        useCORS: true,
      });

      const imgData = canvas.toDataURL('image/png');
      const pdf = new jsPDF('p', 'pt', 'a4');
      const pageWidth = pdf.internal.pageSize.getWidth();
      const pageHeight = pdf.internal.pageSize.getHeight();
      const imgWidth = pageWidth;
      const imgHeight = (canvas.height * imgWidth) / canvas.width;
      let heightLeft = imgHeight;
      let position = 0;

      pdf.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight);
      heightLeft -= pageHeight;

      while (heightLeft > 0) {
        position = heightLeft - imgHeight;
        pdf.addPage();
        pdf.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight);
        heightLeft -= pageHeight;
      }

      const timestamp = new Date().toISOString().replace(/[:.]/g, "-");
      const pdfFileName = `${
        fileName ? fileName.replace(/\.[^/.]+$/, "") : "UFDR"
      }_Report_${timestamp}.pdf`;
      pdf.save(pdfFileName);

    } catch (error) {
      console.error("Failed to generate PDF:", error);
      alert("An error occurred while generating the PDF.");
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <>
      <div style={{ position: 'absolute', left: '-9999px', top: 0 }}>
        <PrintableReport ref={reportRef} queryResult={queryResult} fileName={fileName} />
      </div>

      <div className="report-download-container">
        <button
          type="button"
          className="report-download-button"
          onClick={generatePDFReport}
          disabled={!queryResult || isGenerating}
        >
          <Download className="download-icon" />
          {isGenerating ? 'Generating PDF...' : 'Download Report as PDF'}
          <FileText className="report-icon" />
        </button>
        {!queryResult && (
          <p className="report-download-help">
            Execute a query to generate downloadable report
          </p>
        )}
      </div>
    </>
  );
};

export default ReportDownload;
