import React, { useRef, useState } from 'react';
import { Download, FileText } from 'lucide-react';
import { jsPDF } from 'jspdf';
import html2canvas from 'html2canvas';

// A hidden component styled for the PDF output
const PrintableReport = React.forwardRef(({ queryResult, fileName }, ref) => {
  if (!queryResult) return null;

  return (
    <div ref={ref} className="printable-report">
      <div className="report-header">
        <h1>UFDR Analysis Report</h1>
        <p><strong>Data Source:</strong> {fileName || 'Unknown'}</p>
        <p><strong>Generated on:</strong> {new Date().toLocaleString()}</p>
      </div>

      <div className="report-section">
        <h2>Query Executed</h2>
        <p className="query-text">"{queryResult.query}"</p>
      </div>

      {(queryResult.insights || []).length > 0 && (
        <div className="report-section">
          <h2>Key Insights</h2>
          <ul>
            {(queryResult.insights || []).map((insight, index) => (
              <li key={index}>{insight}</li>
            ))}
          </ul>
        </div>
      )}

      <div className="report-section">
        <h2>Detailed Records</h2>
        <table className="report-table">
          <thead>
            <tr>
              <th>Timestamp</th>
              <th>Type</th>
              <th>Direction</th>
              <th>From</th>
              <th>To</th>
              <th>Location</th>
            </tr>
          </thead>
          <tbody>
            {(queryResult.callLogs || []).map((log, index) => (
              <tr key={index}>
                <td>{new Date(log.timestamp).toLocaleString()}</td>
                <td>{log.callType || "N/A"}</td>
                <td>{log.direction || "N/A"}</td>
                <td>{log.caller_number || "Unknown"}</td>
                <td>{log.receiver_number || "Unknown"}</td>
                <td>{log.location || "N/A"}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      <div className="report-footer">
        <p>Report generated by UFDR Analysis Tool</p>
      </div>
    </div>
  );
});

const ReportDownload = ({ queryResult, fileName }) => {
  const reportRef = useRef(null);
  const [isGenerating, setIsGenerating] = useState(false);

  const generatePDFReport = async () => {
    if (!queryResult || !reportRef.current) {
      alert('No data available to generate report');
      return;
    }

    setIsGenerating(true);

    try {
      const canvas = await html2canvas(reportRef.current, {
        scale: 2,
        useCORS: true,
      });

      const imgData = canvas.toDataURL('image/png');

      // Initialize PDF (A4 size)
      const pdf = new jsPDF('p', 'pt', 'a4');
      const pageWidth = pdf.internal.pageSize.getWidth();
      const pageHeight = pdf.internal.pageSize.getHeight();

      // Scale the image to page width
      const imgWidth = pageWidth;
      const imgHeight = (canvas.height * imgWidth) / canvas.width;

      let heightLeft = imgHeight;
      let position = 0;

      // Function to add header/footer
      const addFooter = (pdf, pageNumber, totalPages) => {
        pdf.setFontSize(10);
        pdf.setTextColor(100);

        // Footer on all pages
        pdf.setFontSize(9);
        pdf.text(
          `Page ${pageNumber} of ${totalPages}`,
          pageWidth / 2,
          pageHeight - 10,
          { align: "center" }
        );
      };

      // First page
      pdf.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight);
      heightLeft -= pageHeight;

      // More pages if needed
      while (heightLeft > 0) {
        position = heightLeft - imgHeight;
        pdf.addPage();
        pdf.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight);
        heightLeft -= pageHeight;
      }

      // Add header/footer to all pages
      const totalPages = pdf.internal.getNumberOfPages();
      for (let i = 1; i <= totalPages; i++) {
        pdf.setPage(i);
        addFooter(pdf, i, totalPages);
      }

      // Timestamped filename
      const timestamp = new Date().toISOString().replace(/[:.]/g, "-");
      const pdfFileName = `${
        fileName ? fileName.replace(/\.[^/.]+$/, "") : "UFDR"
      }_Report_${timestamp}.pdf`;

      pdf.save(pdfFileName);

    } catch (error) {
      console.error("Failed to generate PDF:", error);
      alert("An error occurred while generating the PDF.");
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <>
      <div style={{ position: 'absolute', left: '-9999px', top: 0 }}>
        <PrintableReport ref={reportRef} queryResult={queryResult} fileName={fileName} />
      </div>

      <div className="report-download-container">
        <button
          type="button"
          className="report-download-button"
          onClick={generatePDFReport}
          disabled={!queryResult || isGenerating}
        >
          <Download className="download-icon" />
          {isGenerating ? 'Generating PDF...' : 'Download Report as PDF'}
          <FileText className="report-icon" />
        </button>
        {!queryResult && (
          <p className="report-download-help">
            Execute a query to generate downloadable report
          </p>
        )}
      </div>
    </>
  );
};

export default ReportDownload;
